### ISSUE TITLE
GBT broken, chain stuck on block 1095079

### ISSUE THREAD

**Issue by flound1129** [AppleByteMe/AppleByte#6]
```
$ artbyte-cli getblocktemplate
error code: -1
error message:
CreateNewBlock: TestBlockValidity failed: bad-version (code 17)
```

**Comment by sunk818** [comment]
Compiled new version. It works okay now. Was able to `generate 1 999`
I see one block generated. If any one has asic, now would be a good time to mine as difficulty lowers and others get on the new version...

**Comment by Bushstar** [comment]
The new release resolved this issue. Thanks for the heads up though.

https://github.com/AppleByteMe/AppleByte/releases
