### ISSUE TITLE
.applebyte vs .artbyte

### ISSUE THREAD

**Issue by fogoat** [AppleByteMe/AppleByte#8]
Hi, I notice all the blockchain data goes to `.applebyte` instead of `.artbyte`

Do you see this changing in the future?

I noticed a lot of references to **bitcoin** were renamed to **artbyte**

**Comment by Bushstar** [comment]
ArtByte was originally Applebyte hence it points to the original data directory of .applebyte. Change this and clients will not find the wallet or blockchain data. This is not something easily changed going forward without bespoke code across multiple platforms which will have its own issues.
